name: Azure Blob Storage Site Deploy
description: Azure Blob Storage 静的Webサイト配下へ成果物をデプロイまたはクリーンアップする Composite Action

inputs:
  storage_account:
    description: Azure Storageアカウント名
    required: true
  source_dir:
    description: アップロード対象ディレクトリ（action=deploy の場合に使用）
    required: false
  target_prefix:
    description: "配置先プレフィックス（例: main, pr-42）"
    required: true
  action:
    description: 実行種別（deploy または cleanup）
    required: true

runs:
  using: composite
  steps:
    - name: deploy を実行
      if: ${{ inputs.action == 'deploy' }}
      shell: bash
      env:
        INPUT_STORAGE_ACCOUNT: ${{ inputs.storage_account }}
        INPUT_SOURCE_DIR: ${{ inputs.source_dir }}
        INPUT_TARGET_PREFIX: ${{ inputs.target_prefix }}
        INPUT_ACTION: ${{ inputs.action }}
      run: |
        set -euo pipefail
        "${{ github.action_path }}/scripts/deploy.sh"

    - name: cleanup を実行
      if: ${{ inputs.action == 'cleanup' }}
      shell: bash
      env:
        INPUT_STORAGE_ACCOUNT: ${{ inputs.storage_account }}
        INPUT_TARGET_PREFIX: ${{ inputs.target_prefix }}
        INPUT_ACTION: ${{ inputs.action }}
      run: |
        set -euo pipefail
        "${{ github.action_path }}/scripts/cleanup.sh"
